# Grafana Deployment - runs grafana pod which is accessible through Ingress at http://grafana.frontend.com or NodeIP:30002

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "PROTOCOL://<Domain>:PORT"  # Write the grafana url i.e. http://application-grafana.com:30080
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}

# Grafana Service - exposes grafana as NodePort svc on NodeIP:30002
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30002
