# Sample prometheus configuration file

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9100']  
      
  - job_name: 'backend'
    scrape_interval: 15s
    static_configs:
      - targets: ['backend-service.app:80']

  - job_name: 'frontend'
    scrape_interval: 15s
    static_configs:
      - targets: ['frontend-service.app:80']
      
rule_files:
  - '/etc/prometheus/rules/*.rules'
