# Filebeat as Daemonset

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.12.0
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: var-log
              mountPath: /var/log
          args: ["-c", "/etc/filebeat.yml", "-e"]
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
      restartPolicy: Always
