#=========================== Filebeat inputs =============================

filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/logs/frontend/*
    #- c:\programdata\elasticsearch\logs\*

- type: log
  enabled: true
  paths:
    - /var/logs/backend/*
  fields:
    target_index: third-party-api-metrics
    release_version: 1598.3

# We will give a output location to filebeat which can be logstash

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
 #hosts: ["host1","host2"]
 #loadbalance: true

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"