apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000